version: '3.8'

services:
  # O 'Carteiro' que fará o SAGA funcionar
  rabbitmq:
    image: rabbitmq:3-management
    container_name: dropship_rabbitmq
    ports:
      - "5672:5672"   # Porta onde as APIs se conectam
      - "15672:15672" # Porta do painel visual no navegador
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # O Banco de Dados (usaremos um só contêiner, mas cada API terá seu próprio banco lá dentro)
  mongodb:
    image: mongo:latest
    container_name: dropship_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: