services:
  mongodb:
    image: mongo:latest
    container_name: bazaticket_mongodb
    ports:
      - "27017:27017"
    # 🔥 CRÍTICO: Força o Mongo a rodar em modo Replica Set (Necessário para as Transações do C#)
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    volumes:
      - mongodb_data:/data/db
    networks:
      - bazaticket_network

  # 🔥 CRÍTICO: Este contentor executa o script que liga as transações do cluster
  mongo-init:
    image: mongo:latest
    container_name: bazaticket_mongo_init
    depends_on:
      - mongodb
    networks:
      - bazaticket_network
    command: >
      mongosh --host mongodb:27017 --eval '
      try {
        rs.status();
        console.log("Replica set ja inicializado");
      } catch (e) {
        rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "127.0.0.1:27017" }] });
        console.log("Replica set inicializado com sucesso");
      }'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bazaticket_rabbitmq
    ports:
      - "5672:5672" # Porta da aplicação (onde o C# escuta)
      - "15672:15672" # Painel administrativo visual
    networks:
      - bazaticket_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bazaticket_jaeger
    # 🔥 CRÍTICO: Destranca a porta de escuta para a Telemetria do C# entrar
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - bazaticket_network

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: bazaticket_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - rabbitmq # O n8n só sobe depois do RabbitMQ
    networks:
      - bazaticket_network

volumes:
  mongodb_data:
  n8n_data: 

networks:
  bazaticket_network:
    driver: bridge