version: '3.8'

services:
  # O 'Carteiro' que fará o SAGA funcionar
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bazaticket_rabbitmq
    ports:
      - "5672:5672"   # Porta onde as APIs se conectam
      - "15672:15672" # Porta do painel visual no navegador
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # O Banco de Dados (usaremos um só contêiner, mas cada API terá seu próprio banco lá dentro)
  mongodb:
    image: mongo:latest
    container_name: bazaticket_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: bazaticket_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - rabbitmq

volumes:
  mongo_data: